apiVersion: apps/v1
kind: Deployment
metadata:
  name: drain-test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drain-test
  template:
    metadata:
      labels:
        app: drain-test
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-2
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
