# Linux / KVM libvirt 환경용
# 네트워크: libvirt default NAT (192.168.121.x)
# Ansible 실행 위치: 호스트 Ubuntu 서버

[master]
master ansible_host=192.168.121.10

[workers]
worker-1 ansible_host=192.168.121.11
worker-2 ansible_host=192.168.121.12

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
