# Windows / VirtualBox 환경용
# 네트워크: VirtualBox host-only (192.168.56.x)
# Ansible 실행 위치: WSL2

[master]
master ansible_host=192.168.56.10

[workers]
worker-1 ansible_host=192.168.56.11
worker-2 ansible_host=192.168.56.12

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
