apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-user-token
  namespace: dev
  annotations:
    kubernetes.io/service-account.name: dev-user
type: kubernetes.io/service-account-token
