apiVersion: v1
kind: Pod
metadata:
  name: maintenance-pod
  namespace: default
spec:
  tolerations:
    - key: "env"
      operator: "Equal"
      value: "maintenance"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        requests:
          cpu: "50m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
