apiVersion: v1
kind: Pod
metadata:
  name: log-pod
  namespace: default
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: app
      image: busybox:latest
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do echo $(date) >> /var/log/app.log; sleep 5; done"
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

    - name: sidecar
      image: busybox:latest
      command:
        - "/bin/sh"
        - "-c"
        - "tail -f /var/log/app.log"
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
